// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5CgB4K9yocXWcZSkIgfFg9JGmCRqTxPc',
    appId: '1:1061664889869:web:50bc4db07bef604e644944',
    messagingSenderId: '1061664889869',
    projectId: 'track-warranty-78ded',
    authDomain: 'track-warranty-78ded.firebaseapp.com',
    storageBucket: 'track-warranty-78ded.appspot.com',
    measurementId: 'G-6N9ZF1B82Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOX7TNgTUmj2SLITWS7iHjR0iD6d1y3VI',
    appId: '1:1061664889869:android:bf6a6e87b8303157644944',
    messagingSenderId: '1061664889869',
    projectId: 'track-warranty-78ded',
    storageBucket: 'track-warranty-78ded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpKET2eVdWbV3CYB7zCYM8DRQCTCzTDhk',
    appId: '1:1061664889869:ios:c68dcd8b916f8d9f644944',
    messagingSenderId: '1061664889869',
    projectId: 'track-warranty-78ded',
    storageBucket: 'track-warranty-78ded.appspot.com',
    iosBundleId: 'com.example.warrantyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpKET2eVdWbV3CYB7zCYM8DRQCTCzTDhk',
    appId: '1:1061664889869:ios:c68dcd8b916f8d9f644944',
    messagingSenderId: '1061664889869',
    projectId: 'track-warranty-78ded',
    storageBucket: 'track-warranty-78ded.appspot.com',
    iosBundleId: 'com.example.warrantyTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5CgB4K9yocXWcZSkIgfFg9JGmCRqTxPc',
    appId: '1:1061664889869:web:ff879848f362cb34644944',
    messagingSenderId: '1061664889869',
    projectId: 'track-warranty-78ded',
    authDomain: 'track-warranty-78ded.firebaseapp.com',
    storageBucket: 'track-warranty-78ded.appspot.com',
    measurementId: 'G-FM8S315JYW',
  );
}
